### ISSUE TITLE
Basicアップデート機能

### ISSUE THREAD

**Issue by mtoksuy** [mtoksuy/basic#19]
## 仕様

1. ローカルでも本番でも機能すること
2. コマンドは使わない(使えない
3. root内部、かつphpのみで完結
4. ユーザー使用ディレクトリは触れない
5. admin部分のみ変更(setting と app/theme/admin )

## 実装する上での注意点

1. basic::copy_dir関数がキモ
2. 書き換えるディレクトリは setting と app/theme/admin のみ
3. 将来的に app/assets/ も変更される可能性はあるが、一旦はスルー。変更時には部分変更になると思われるので再度改修が必要。
4. 現状の仕様は **差分も見ないで書き換え** なのでまた近い内に改修する可能性あり。

## Basicアップデート機能の流れ
1. 自身のバージョンと最新バージョンを比較
2. 古いバージョンの場合、最新バージョンのzipを取得する(tmp配下に配置して解凍)
3. ユーザーがいじらないadmin部分を最新バージョンのファイルに書き換え
4. tmpディレクトリ削除

**Comment by mtoksuy** [comment]
PL
https://github.com/mtoksuy/basic/pull/61

commit
version_0.7 Basicアップデート機能https://github.com/mtoksuy/basic/issues/19 下準備
https://github.com/mtoksuy/basic/pull/61/commits/1918b25d185cd14c816719e053f77840d928bdc6
・コアアップデートコントローラー作成
・ディレクトリをコピーするcopy_dir関数拝借
・setting テーブル：basic_versionカラム追加
・テスト用でtmp配下をcommitしないよう制御

**Comment by mtoksuy** [comment]
admin部分書き換え(setting と app/theme/admin )テストを行うため、一旦PL( #61 )をマージする。

**Comment by mtoksuy** [comment]
PL
https://github.com/mtoksuy/basic/pull/64

commit
https://github.com/mtoksuy/basic/pull/64/commits/a03510738dc75bced770e806b16c43fc2b787608

ほぼ完成。あとはテストを行うのみ。

**Comment by mtoksuy** [comment]
テスト成功。
・最新のバージョンに書き換え成功
・DB、settingのbasic_version書き換え成功
・他のディレクトリに影響なし

**Comment by mtoksuy** [comment]
commit
https://github.com/mtoksuy/basic/pull/64/commits/b59ea9ead26ae53d7f6b4545f32dbe3f6a731bcd

**Comment by pipelinevp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
gerryyang, @workwyz, @bqxu, @0x2a94b5, @ruoshan, @RojerAlone, @moumc, @hottech-jxd, @shunkit, @zx68555, @ajaybirla, @CosmicWebServices, @chudongfang, @liudeyan, @Aiden01, @karmaQ, @abir1729, @codingrider, @gtdalp, @marsprince, @seawind82, @Jabbs, @aryanbaghi, @seungjuchae, @Lazybones3, @wangwuqi, @NinjaGrassMaster, @luxkun, @michaelkuty, @ikaiguang, @qifengzhou, @guanchaoguo, @Richard-Faust, @Annihilater, @nick6969, @skyrocketZ, @timerish, @mewfree, @mtleliever, @javalight, @cizi2018, @josemvcerqueira, @simonracz, @moonflow, @Shwetank30, @gldeng, @yg-x, @aalmost, @chenleji, @kofikong
